Repository ProjectAnni/book, pull requests merged in 2021-12, with the labels that each got.

#2 [Draft] Annil 歌词分发
  src/05.audio-library/01.protocol.md
Labels: documentation, enhancement

#11 补充用户信息部分
  src/06.anniv/02.user.md
  src/06.anniv/features/02.2fa.md
Labels: enhancement

#12 [Draft] Anniv 元数据接口
  src/06.anniv/08.meta.md
  src/06.anniv/09.search.md
  src/SUMMARY.md
Labels: enhancement

#9 预构建数据源
  src/02.metadata-repository/06.metdata-db.md
  src/SUMMARY.md
Labels: enhancement

#13 接口：获取 Annil 信息
  src/05.audio-library/01.protocol.md
Labels: enhancement

#28 取消 Annil 封面鉴权
  src/05.audio-library/01.protocol.md
Labels: enhancement

#27 艺术家名转义规则
  src/01.audio-convention/04.zzzz.02.artist.md
Labels: bug

#29 `TrackInfoWithAlbum` 中增加专辑标题
  src/06.anniv/08.meta.md
  src/06.anniv/10.favorite.md
Labels: enhancement
